author: Chris Zuber
title: Kern Valley Rafting
url: 'https://rafting.kernvalley.us'
markdown: kramdown
version: 1.0.0
timezone: America/Los_Angeles
lang: en
dir: ltr
charset: utf-8
paginate: 8
paginate_path: "/page-:num/"
viewport: width=device-width
robots: 'follow,index'
referrer: origin-when-cross-origin
manifest: /manifest.json
tiles-config: /browserconfig.xml
service_worker: /service-worker.js
og-type: website
description: "Rafting info about the Kern Valley"
mobile-web-app-capable: true
publisher: 'https://plus.google.com/113117303106986445610'
canonical: 'https://rafting.kernvalley.us'
contextmenu: nav-menu
body-class: 'background-primary grid border-box cursor-default font-main'
feature-detect:
- details
- dialog
keywords:
- kern valley
- kern river valley
- rafting
- whitewater
repository:
  username: kernvalley
  title: rafting.kernvalley.us
  url: 'https://github.com/kernvalley/rafting.kernvalley.us'
twitter: kern_valley
facebook-id: 2123017744629045
feed:
  url: /feed.rss
  type: application/rss+xml
icons: '/img/icons.svg'
logo: rafting
theme-color: '#0031c6'
background-color: '#242424'
discus-identifier: kernvalley-us
google-analytics: UA-119717465-2
# ad-sense:
webmaster-verifications:
 google: Ki2pY_ejBGKRgpRxNYH5GZgOBLHqfD2krm7uF30ItKY
#  bing:
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: Chris Zuber
    permalink: /:categories/:year/:month/:day/:title/
    comments: true
    ads: false
    index: true
- scope:
    path: _drafts
  values:
    layout: post
    author: Chris Zuber
    permalink: /posts/:categories/:year/:month/:day/:title/
    comments: false
    ads: false
plugins:
- jekyll-watch
- jekyll-paginate
include:
- _headers
- _redirects
- .well-known/
exclude:
- "*.rb"
- "*.gemspec"
- "*.php"
- "*.sh"
- "*.csv"
- "*.sfd"
- "*.ai"
- "*.psd"
- "*.sketch"
- "*.yml"
- "*.lock"
- "*.log"
- "/css/*.md"
- "/js/*.md"
- "/img/*.md"
- "/fonts/*.md"
- "/js/*.json"
- "/package.json"
- "/package-lock.json"
- "/js/svg4everybody/dist/"
- "/js/svg4everybody/test/"
- "/css/animate.css/source/"
- docs/
- "/css/*.json"
- "/img/*.json"
- "/js/*.html"
- Gemfile
- node_modules/
- palette.xml
- postcss.config.js
- postcss.config.json
- README.md
- LICENSE
- "*.config.js"
- "/img/adwaita-icons/docs"
- "/img/adwaita-icons/LICENSE"
- "css/core-css/docs"
- "css/normalize/*.html"
- "js/std-js/docs"
- "js/std-js/test"
